/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alany_analysejvm_lecture32_Foo */

#ifndef _Included_com_alany_analysejvm_lecture32_Foo
#define _Included_com_alany_analysejvm_lecture32_Foo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alany_analysejvm_lecture32_Foo
 * Method:    foo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alany_analysejvm_lecture32_Foo_foo
  (JNIEnv *, jclass);

/*
 * Class:     com_alany_analysejvm_lecture32_Foo
 * Method:    bar
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_alany_analysejvm_lecture32_Foo_bar__IJ
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_alany_analysejvm_lecture32_Foo
 * Method:    bar
 * Signature: (Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_com_alany_analysejvm_lecture32_Foo_bar__Ljava_lang_String_2_3I
  (JNIEnv *, jobject, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
